### ISSUE TITLE
Unbonding Requests limit may cause network stuck

### ISSUE THREAD

**Issue by Jianzhuo** [subquery/network-contracts#159]
###  **Issue Review:**

Since we add indexers' commission SQT rewards to Unbonding Requests list every time collectAndDistributeRewards, if the Unbonding Requests limit reached, collectAndDistributeRewards and unstake operation will be revert.

###  **Why we need set a limitation of Unbonding Requests?** 

The main reason is we priority slash the indexer from its Unbonding Requests, traverse the Unbonding Requests list is required in this algorithm, for which it is necessary to limit the Unbonding Requests size.

###  **Solution 1**

We can withdraw before collectAndDistributeRewards, but it may not solve this problem, it is possible that all the Unbonding Requests not pass the lockPeriod, no one can be withdraw.

### **Solution 2**

At collectAndDistributeRewards, if the Unbonding Requests reaches limit, we can add the commission SQT rewards to the latest  Unbonding Requests, and renew its lockPeriod.

**Comment by mzxyz** [comment]
# Proposal - V1
## Issue

There has cycle dependency issue between `add new unbonding` and `collect rewards` when indexer don't withdraw the unlocked unbonding in time and make the unbonding records reach the limitation.

## Solution (14/03/2023)

We plan to split the `unbonding` to 2 parts:
- One is from `rewards` (indexer commission fee)
- Another is from `unstake` and `undelegate`

The data structure for `Unbonding`:

```
struct Unbonding {
    mapping(uint256 => UnbondingAmount) rewards;
    mapping(uint256 => UnbondingAmount) staking;
    uint256 rewardsStart;    // use to record the last withdraw index
    uint256 rewardsNext;    // use to record the index of latest unbonding record
    uint256 stakingStart;
    uint256 stakingNext;
}
```

The limitation for `rewards` and `staking` will be different:

```
// Max length of unbonding rewards, set 5 as default value
uint256 public maxUnbondingRewards;

// Max length of unbonding staking, set 15 as default value
uint256 public maxUnbondingStaking;
```

- When`staking` unbonding reach the limitation, user will not be able to add new unbonding until withdraw the unlocked records.
- When `rewards` unbonding reach the limitations, the new unbonding value will add to the last record which will not block the `collect rewards`.

To apply these new changes to `unbonding` functions, we need to check the `unbonding type` every time and apply different operation to `rewards` and `staking`.

Draft PR #163

**Comment by mzxyz** [comment]
# Proposal - V2

## Issue

There has cycle dependency issue between add new unbonding and collect rewards when indexer don't withdraw the unlocked unbonding in time and make the unbonding records reach the limitation.

## Solution

We still use the `maxUnbondingLength` to control the max unbonding records. In order to resolve the issue, we introduce a limitation for unbonding request from `undelegate` action:

- This kind of unbonding request can only use the first  `maxUnbondingLength -1` space to add new unbonding. If `undelegate` reach the limitation, it will failed directly.
- The space at `maxUnbondingLength` only use for `unstaking` and `commission rate` type. When the these kind of unbonding reach the the limitation, the new request will merge with the last unbonding records.
