### ISSUE TITLE
The code style of the contract

### ISSUE THREAD

**Issue by nz-neooo** [subquery/network-contracts#26]
We need to unify the code format in the contract.
Especially documentation comments and revert message.

**Comment by neo-sun** [comment]
Yeah, we need discuss this code style, I find we have added the [prettier](https://github.com/prettier-solidity/prettier-plugin-solidity). and maybe we need do more about it. And uniform for code comments, interface order, etc.

Some ideas for discuss.
- interface order
  - `struct` outside the `contract` or move to `interface` contract. That will easy use for other contracts.
  - the order is
    1. Top is our License and pragma version
    1. `properties`
    1. `public (tx effect)`
    1. `public external`
    1. `public view`
    1. `public external view`
    1. `private (tx effect)`
    1. `private view`
- comments
  - comment for `properties` and `function`: use multiple, like `/* \n xxx \n */`.
  - comment with multiple, use ` . ` at last words.
  - comment for code: use line with a space, like `// Xxx.`
  - comment first words use upcase, and also has `.` at last words. Like `// This is some xxx.`
- revert message
  - short and simple (less than 5 words, two words maybe better)
  - If revert caused by some check, use same message.

continue...

**Comment by Jianzhuo** [comment]
We may build a table to map the revert code and revert message, so in the contract we can use the code instead of revert message:

G --- General revert
S --- Staking relate revert
R --- Reward relate revert
I --- Indexer relate revert

| Revert Code | Revert Message |
|----------|:-------------:|
| G001 |  Integer Overflow and Underflow |
| S001 |  Caller is not indexer |
| .... | ... |
